# Generated by Django 3.2.9 on 2022-11-03 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='', max_length=2000)),
                ('HOSTNAME', models.CharField(default='', max_length=2000)),
                ('LOGGING', models.CharField(default='', max_length=2000)),
                ('local_credentials', models.CharField(default='', max_length=2000)),
                ('TACACS', models.CharField(default='', max_length=2000)),
                ('STEALTHWATCH_FLOW_RECORD', models.CharField(default='', max_length=2000)),
                ('NETFLOW_TO_STEALTHWATCH', models.CharField(default='', max_length=2000)),
                ('IPv4_NETFLOW', models.CharField(default='', max_length=2000)),
                ('MGMT_ACCESS_ACL', models.CharField(default='', max_length=2000)),
                ('SNMP_RO_ACL', models.CharField(default='', max_length=2000)),
                ('SNMP_RW_ACL', models.CharField(default='', max_length=2000)),
                ('SNMP', models.CharField(default='', max_length=2000)),
                ('LINE_CON0', models.CharField(default='', max_length=2000)),
                ('LINE_AUX0', models.CharField(default='', max_length=2000)),
                ('LINE_VTY0_4', models.CharField(default='', max_length=2000)),
                ('LINE_VTY5_15', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='LatestRunningConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostname', models.CharField(default='', max_length=255)),
                ('compliance_type', models.CharField(choices=[('Grn200Lo200', 'Has Grn200 vrf and has L200'), ('Grn200NoLo200', 'Has Grn200 vrf and No L200'), ('NoGrn200Lo200', 'No Grn200 vrf but has L200'), ('NoGrn200NoLo200', 'No Grn200 vrf and No L200')], default='Grn200Lo200', max_length=25)),
                ('running_config', models.TextField(default='', max_length=100000)),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
